### ISSUE TITLE
Translation of GUI

### ISSUE THREAD

**Issue by elazarg** [haitham-kablan/Yearly_project#11]
The project should (ideally) be easy to translate to different languages. How do we do that?

**Comment by elazarg** [comment]
* There's a guide for doing that in Flutter: https://flutter.dev/docs/development/accessibility-and-localization/internationalization
* Also there's a guide for an extension: https://medium.com/flutter-community/i18n-extension-flutter-b966f4c65df9 (I think the guide is easier to read)

Also take a look at the [accessibility guide](https://flutter.dev/docs/development/accessibility-and-localization/accessibility).

**Comment by AbuJabal-Hussein** [comment]
- the default language of the app is the default language of the device
- the user can change the language of the app as he likes

implementation note: we can save the language of the app either in firebase or in a file in the device

**Comment by AbuJabal-Hussein** [comment]
Done.
