### ISSUE TITLE
Allow users to remove themselves

### ISSUE THREAD

**Issue by elazarg** [haitham-kablan/Yearly_project#23]

**Comment by haitham-kablan** [comment]
can you please provide more explaintaion , what do you excatly mean?

**Comment by AbuJabal-Hussein** [comment]
It means that if a user doesn't want to be registerd in the appication
anymore, he should be able to delete himself.
So we should add a button in his profile to that provides this
functionality.
There is a function in the firebase/flutter wesite, under the tab
authentication, that allowes the user to remove himself.. but note that we
should (carefully) remove some more information regarding the help-requests
that he is involved in.

**Comment by haitham-kablan** [comment]
working on it

**Comment by haitham-kablan** [comment]
Done
