### ISSUE TITLE
Sign out is not working well

### ISSUE THREAD

**Issue by haitham-kablan** [haitham-kablan/Yearly_project#8]
when i press sign out i return to the login page whcih is good. but the stack isnt empty (if i press back button in loginpages it returns to the previous user, instaed of totally closing the app).
this also causes errors

**Comment by AbuJabal-Hussein** [comment]
@haitham-kablan 
if you're working on it right now, try to put this in the code of sign-out: ( replace LoginPage() with the appropriate name )

Navigator.pushAndRemoveUntil(
      context,
      MaterialPageRoute(
        builder: (BuildContext context) => LoginPage(),
      ),
      (route) => false,
    );

instead of the current Navigator.push line
tell me if it works.. if it doesn't work I will try to fix it

**Comment by haitham-kablan** [comment]
This is what i was doing but it doesnt work(I think it is as same as hannen
problem iam changing context and stuff) , any way it is in fubction called
sign out inside data base services , give it a check!
